import { HerbivoreGene, PathogenGene, PlantGene } from './genes'

export const HERBIVORE_GENE_LABELS: Record<number, string> = {
  [HerbivoreGene.Speed]: 'Speed',
  [HerbivoreGene.Size]: 'Size',
  [HerbivoreGene.Metabolism]: 'Metabolism',
  [HerbivoreGene.Vision]: 'Vision',
  [HerbivoreGene.ReproThreshold]: 'Repro threshold',
  [HerbivoreGene.MaxAge]: 'Max age',
  [HerbivoreGene.ForageEfficiency]: 'Forage efficiency',
  [HerbivoreGene.OffspringGift]: 'Offspring gift',
  [HerbivoreGene.Hue]: 'Hue',
  [HerbivoreGene.Saturation]: 'Saturation',
  [HerbivoreGene.Shape]: 'Shape',
  [HerbivoreGene.HungerDrive]: 'Hunger drive',
  [HerbivoreGene.SleepNeed]: 'Sleep need',
  [HerbivoreGene.FatigueRate]: 'Fatigue rate',
  [HerbivoreGene.SleepRecovery]: 'Sleep recovery',
  [HerbivoreGene.Libido]: 'Libido',
  [HerbivoreGene.SatietyBuffer]: 'Satiety buffer',
  [HerbivoreGene.MaxEnergy]: 'Max energy',
  [HerbivoreGene.ReproCooldown]: 'Repro cooldown',
  [HerbivoreGene.MateRange]: 'Mate range',
  [HerbivoreGene.SleepMobility]: 'Sleep mobility',
  [HerbivoreGene.SleepMetabolism]: 'Sleep metabolism',
  [HerbivoreGene.BitePower]: 'Bite power',
  [HerbivoreGene.ForageReach]: 'Forage reach',
  [HerbivoreGene.ModeCommitment]: 'Mode commitment',
  [HerbivoreGene.Wanderlust]: 'Wanderlust',
  [HerbivoreGene.ExploreVision]: 'Explore vision',
  [HerbivoreGene.Maturation]: 'Maturation',
  [HerbivoreGene.Gestation]: 'Gestation',
  [HerbivoreGene.BirthReserve]: 'Birth reserve',
  [HerbivoreGene.SexExpression]: 'Sex expression',
  [HerbivoreGene.PreferredHue]: 'Preferred hue',
  [HerbivoreGene.PreferredSize]: 'Preferred size',
  [HerbivoreGene.PreferredSpeed]: 'Preferred speed',
  [HerbivoreGene.MateSelectivity]: 'Mate selectivity',
  [HerbivoreGene.GeneticAssortment]: 'Genetic assortment',
  [HerbivoreGene.SpaceTolerance]: 'Space tolerance',
  [HerbivoreGene.Aggressiveness]: 'Aggressiveness',
  [HerbivoreGene.MutationRate]: 'Mutation rate',
  [HerbivoreGene.MutationAmount]: 'Mutation amount',
  [HerbivoreGene.CannibalPredilection]: 'Dissimilar predation',
  [HerbivoreGene.PlantHardiness]: 'Hardy forage',
  [HerbivoreGene.PlantForageSelectivity]: 'Forage selectivity',
  [HerbivoreGene.BodyElongation]: 'Body elongation',
  [HerbivoreGene.BodySpikiness]: 'Body spikiness',
  [HerbivoreGene.BodyMarking]: 'Body markings',
  [HerbivoreGene.DiseaseResistance]: 'Disease resistance',
  [HerbivoreGene.DiseaseRecovery]: 'Disease recovery',
  [HerbivoreGene.InbreedingTolerance]: 'Inbreeding tolerance',
  [HerbivoreGene.Contagion]: 'Contagion',
  [HerbivoreGene.CourtshipEagerness]: 'Courtship eagerness',
  [HerbivoreGene.CloseMateLeniency]: 'Close mate leniency',
  [HerbivoreGene.Cohesion]: 'Cohesion',
}

export const PLANT_GENE_LABELS: Record<number, string> = {
  [PlantGene.GreenHue]: 'Green hue',
  [PlantGene.Saturation]: 'Saturation',
  [PlantGene.Lightness]: 'Lightness',
  [PlantGene.MaxEnergy]: 'Max energy',
  [PlantGene.GrowthRate]: 'Growth rate',
  [PlantGene.SpreadMin]: 'Spread min',
  [PlantGene.SpreadMax]: 'Spread max',
  [PlantGene.Maturation]: 'Maturation',
  [PlantGene.Reproduction]: 'Reproduction',
  [PlantGene.BaseRadius]: 'Base radius',
  [PlantGene.MutationRate]: 'Mutation rate',
  [PlantGene.MutationAmount]: 'Mutation amount',
  [PlantGene.Hardiness]: 'Hardiness',
  [PlantGene.LeafLobes]: 'Leaf lobes',
  [PlantGene.LeafPointiness]: 'Leaf pointiness',
}

export const PATHOGEN_GENE_LABELS: Record<number, string> = {
  [PathogenGene.Antigen0]: 'Antigen A',
  [PathogenGene.Antigen1]: 'Antigen B',
  [PathogenGene.Antigen2]: 'Antigen C',
  [PathogenGene.Virulence]: 'Virulence',
  [PathogenGene.Transmissibility]: 'Transmissibility',
}
