import { HerbivoreGene, PathogenGene, PlantGene } from './genes'

export const HERBIVORE_GENE_LABELS: Record<number, string> = {
  [HerbivoreGene.Speed]: 'Speed',
  [HerbivoreGene.Size]: 'Size',
  [HerbivoreGene.Metabolism]: 'Metabolism',
  [HerbivoreGene.Vision]: 'Vision',
  [HerbivoreGene.ReproThreshold]: 'Repro threshold',
  [HerbivoreGene.MaxAge]: 'Max age',
  [HerbivoreGene.ForageEfficiency]: 'Forage efficiency',
  [HerbivoreGene.OffspringGift]: 'Offspring gift',
  [HerbivoreGene.Hue]: 'Hue',
  [HerbivoreGene.Saturation]: 'Saturation',
  [HerbivoreGene.Shape]: 'Shape',
  [HerbivoreGene.HungerDrive]: 'Hunger drive',
  [HerbivoreGene.SleepNeed]: 'Sleep need',
  [HerbivoreGene.FatigueRate]: 'Fatigue rate',
  [HerbivoreGene.SleepRecovery]: 'Sleep recovery',
  [HerbivoreGene.Libido]: 'Libido',
  [HerbivoreGene.SatietyBuffer]: 'Satiety buffer',
  [HerbivoreGene.MaxEnergy]: 'Max energy',
  [HerbivoreGene.ReproCooldown]: 'Repro cooldown',
  [HerbivoreGene.MateRange]: 'Mate range',
  [HerbivoreGene.SleepMobility]: 'Sleep mobility',
  [HerbivoreGene.SleepMetabolism]: 'Sleep metabolism',
  [HerbivoreGene.BitePower]: 'Bite power',
  [HerbivoreGene.ForageReach]: 'Forage reach',
  [HerbivoreGene.ModeCommitment]: 'Mode commitment',
  [HerbivoreGene.Wanderlust]: 'Wanderlust',
  [HerbivoreGene.ExploreVision]: 'Explore vision',
  [HerbivoreGene.Maturation]: 'Maturation',
  [HerbivoreGene.Gestation]: 'Gestation',
  [HerbivoreGene.BirthReserve]: 'Birth reserve',
  [HerbivoreGene.SexExpression]: 'Sex expression',
  [HerbivoreGene.PreferredHue]: 'Preferred hue',
  [HerbivoreGene.PreferredSize]: 'Preferred size',
  [HerbivoreGene.PreferredSpeed]: 'Preferred speed',
  [HerbivoreGene.MateSelectivity]: 'Mate selectivity',
  [HerbivoreGene.GeneticAssortment]: 'Genetic assortment',
  [HerbivoreGene.SpaceTolerance]: 'Space tolerance',
  [HerbivoreGene.Aggressiveness]: 'Aggressiveness',
  [HerbivoreGene.MutationRate]: 'Mutation rate',
  [HerbivoreGene.MutationAmount]: 'Mutation amount',
  [HerbivoreGene.CannibalPredilection]: 'Dissimilar predation',
  [HerbivoreGene.PlantHardiness]: 'Hardy forage',
  [HerbivoreGene.PlantForageSelectivity]: 'Forage selectivity',
  [HerbivoreGene.BodyElongation]: 'Body elongation',
  [HerbivoreGene.BodySpikiness]: 'Body spikiness',
  [HerbivoreGene.BodyMarking]: 'Body markings',
  [HerbivoreGene.DiseaseResistance]: 'Disease resistance',
  [HerbivoreGene.DiseaseRecovery]: 'Disease recovery',
  [HerbivoreGene.InbreedingTolerance]: 'Inbreeding tolerance',
  [HerbivoreGene.Contagion]: 'Contagion',
  [HerbivoreGene.CourtshipEagerness]: 'Courtship eagerness',
  [HerbivoreGene.CloseMateLeniency]: 'Close mate leniency',
  [HerbivoreGene.Cohesion]: 'Cohesion',
  [HerbivoreGene.WaterSource]: 'Water source',
  [HerbivoreGene.Memory]: 'Memory',
}

/** Plain-language effect of each herbivore gene — shown in the creature editor. */
export const HERBIVORE_GENE_DESCRIPTIONS: Record<number, string> = {
  [HerbivoreGene.Speed]: 'How fast the creature moves while awake. Higher values mean quicker foraging, fleeing, and mate chases.',
  [HerbivoreGene.Size]: 'Body radius. Larger creatures store more energy and hit harder, but need more food to stay alive.',
  [HerbivoreGene.Metabolism]: 'Energy burned every tick while awake. High metabolism needs constant eating.',
  [HerbivoreGene.Vision]: 'Detection range for plants, mates, prey, and nearby creatures.',
  [HerbivoreGene.ReproThreshold]: 'Minimum energy required before the creature can enter mating or pregnancy.',
  [HerbivoreGene.MaxAge]: 'Maximum lifespan. When age exceeds this, the creature dies of old age.',
  [HerbivoreGene.ForageEfficiency]: 'Energy gained per bite of plant. Works with bite power to determine harvest amount.',
  [HerbivoreGene.OffspringGift]: 'Energy transferred to a newborn at birth — a head start for the next generation.',
  [HerbivoreGene.Hue]: 'Body color on the hue wheel (0–360°). Also used when comparing dissimilarity for predation.',
  [HerbivoreGene.Saturation]: 'How vivid the body color is, and partly how light it appears.',
  [HerbivoreGene.Shape]: 'Base silhouette: round, oval, square, or triangle. Combined with elongation and spikiness for the final look.',
  [HerbivoreGene.HungerDrive]: 'Energy level where hunger kicks in and the creature prioritizes finding food.',
  [HerbivoreGene.SleepNeed]: 'How tired the creature must get before it stops to sleep. Higher = sleeps sooner.',
  [HerbivoreGene.FatigueRate]: 'How quickly tiredness builds while awake and moving.',
  [HerbivoreGene.SleepRecovery]: 'How fast fatigue drops and energy recovers while sleeping.',
  [HerbivoreGene.Libido]: 'Baseline sex drive. Higher libido makes mate-seeking more urgent once other needs are met.',
  [HerbivoreGene.SatietyBuffer]: 'Extra energy above the hunger line before the creature feels fully sated.',
  [HerbivoreGene.MaxEnergy]: 'Energy storage cap. Must fill this (and meet repro threshold) to reproduce.',
  [HerbivoreGene.ReproCooldown]: 'Minimum time after mating or birth before the creature can mate again.',
  [HerbivoreGene.MateRange]: 'How close a partner must be for courtship and mating attempts.',
  [HerbivoreGene.SleepMobility]: 'Movement speed while asleep. Low values mean the creature barely drifts; high values mean restless sleep.',
  [HerbivoreGene.SleepMetabolism]: 'Metabolic rate multiplier while sleeping. Lower saves energy overnight.',
  [HerbivoreGene.BitePower]: 'Strength of each bite on plants and other creatures. Adds to attack damage.',
  [HerbivoreGene.ForageReach]: 'How close the creature must get to a plant before it can eat.',
  [HerbivoreGene.ModeCommitment]: 'Ticks before reconsidering the current goal (forage, mate, wander). Higher = stickier behavior.',
  [HerbivoreGene.Wanderlust]: 'How long random wandering lasts before picking a new destination.',
  [HerbivoreGene.ExploreVision]: 'Vision range multiplier while exploring. Helps discover distant food and mates.',
  [HerbivoreGene.Maturation]: 'Age before adulthood. Immature creatures cannot reproduce.',
  [HerbivoreGene.Gestation]: 'Pregnancy length for females, in simulation ticks.',
  [HerbivoreGene.BirthReserve]: 'Minimum energy kept after giving birth so the mother is not left empty.',
  [HerbivoreGene.SexExpression]: 'Gene-level sex bias. The Sex dropdown above overrides this for saved genomes; offspring inherit from DNA.',
  [HerbivoreGene.PreferredHue]: 'Ideal mate body color. Attraction drops as a partner’s hue diverges from this preference.',
  [HerbivoreGene.PreferredSize]: 'Ideal mate size (0–100% scale). Used when scoring potential partners.',
  [HerbivoreGene.PreferredSpeed]: 'Ideal mate speed (0–100% scale). Used when scoring potential partners.',
  [HerbivoreGene.MateSelectivity]: 'How picky the creature is. Higher values require a stronger attraction score to accept a mate.',
  [HerbivoreGene.GeneticAssortment]: 'Preferred DNA similarity in mates. High = prefers relatives; low = prefers genetically distant partners.',
  [HerbivoreGene.SpaceTolerance]: 'Comfort with crowding. Low values demand large personal space; high values tolerate dense groups.',
  [HerbivoreGene.Aggressiveness]: 'Likelihood and intensity of attacking other creatures. Feeds into attack damage.',
  [HerbivoreGene.MutationRate]: 'Chance each gene mutates when offspring are born.',
  [HerbivoreGene.MutationAmount]: 'Typical size of an allele change when a mutation occurs (small nudges vs larger jumps).',
  [HerbivoreGene.CannibalPredilection]: 'Willingness to hunt and eat creatures that look genetically different. Drives carnivore-style behavior.',
  [HerbivoreGene.PlantHardiness]: 'Ability to break through tough, hardy plants that resist weaker foragers.',
  [HerbivoreGene.PlantForageSelectivity]: 'Preference for certain plant lineages when choosing what to eat.',
  [HerbivoreGene.BodyElongation]: 'Stretches the body silhouette vertically. Affects the rendered shape.',
  [HerbivoreGene.BodySpikiness]: 'Adds spikes and wobble to the body outline.',
  [HerbivoreGene.BodyMarking]: 'Inner marking overlay on the body. Higher values show a stronger secondary pattern.',
  [HerbivoreGene.DiseaseResistance]: 'How well the creature resists catching infections from others or the environment.',
  [HerbivoreGene.DiseaseRecovery]: 'How quickly the creature clears an active infection.',
  [HerbivoreGene.InbreedingTolerance]: 'How much inbreeding depression offspring can tolerate when related parents mate.',
  [HerbivoreGene.Contagion]: 'How readily the creature spreads disease to others while infected.',
  [HerbivoreGene.CourtshipEagerness]: 'How sated the creature must be before seeking mates. Higher = enters horny mode sooner after eating.',
  [HerbivoreGene.CloseMateLeniency]: 'Relaxes mate pickiness when a partner is already within physical mate range.',
  [HerbivoreGene.Cohesion]: 'Pull toward nearby genetically similar creatures — drifts with the herd instead of wandering alone.',
  [HerbivoreGene.WaterSource]:
    'Where the creature hydrates: low = pond, high = plant forage (tissue water in bites). Affects thirsty movement and drinking.',
  [HerbivoreGene.Memory]:
    'Spatial recall for water and food. Low = forgets quickly and wanders blindly; high = remembers pond shores and rich foraging patches and returns when thirsty or hungry.',
}

export const PLANT_GENE_LABELS: Record<number, string> = {
  [PlantGene.GreenHue]: 'Green hue',
  [PlantGene.Saturation]: 'Saturation',
  [PlantGene.Lightness]: 'Lightness',
  [PlantGene.MaxEnergy]: 'Max energy',
  [PlantGene.GrowthRate]: 'Growth rate',
  [PlantGene.SpreadMin]: 'Spread min',
  [PlantGene.SpreadMax]: 'Spread max',
  [PlantGene.Maturation]: 'Maturation age — also affects maximum lifespan.',
  [PlantGene.Reproduction]: 'Reproduction',
  [PlantGene.BaseRadius]: 'Base radius',
  [PlantGene.MutationRate]: 'Mutation rate',
  [PlantGene.MutationAmount]: 'Mutation amount',
  [PlantGene.Hardiness]: 'Drought tolerance and lifespan — tougher plants wilt slower and live longer.',
  [PlantGene.LeafLobes]: 'Leaf lobes',
  [PlantGene.LeafPointiness]: 'Leaf pointiness',
  [PlantGene.Kind]: 'Lineage kind',
  [PlantGene.MoistureNeed]: 'Moisture need',
  [PlantGene.TempPreference]: 'Temp preference',
  [PlantGene.TempGrowthRange]: 'Temp growth range',
  [PlantGene.TempSurvivalRange]: 'Temp survival margin',
}

export const PATHOGEN_GENE_LABELS: Record<number, string> = {
  [PathogenGene.Antigen0]: 'Antigen A',
  [PathogenGene.Antigen1]: 'Antigen B',
  [PathogenGene.Antigen2]: 'Antigen C',
  [PathogenGene.Virulence]: 'Virulence',
  [PathogenGene.Transmissibility]: 'Transmissibility',
}
